### ISSUE TITLE
Better install instructions

### ISSUE THREAD

**Issue by RobotRoss** [jurkovic-nikola/OpenLinkHub#1]
**Is your feature request related to a problem? Please describe.**
Yes - The install instructions provided assume the user is a developer themselves, and does not provide a simple way to get the program running on their system, requiring manual troubleshooting (due to multiple things, e.g. SELinux policy not allowing services to run from the home directory by default) which the user may not be able to do.

**Describe the solution you'd like**
Add a section to the readme for instructions for non-developers to get the program running on their system.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by jurkovic-nikola** [comment]
Hello,

Thanks for reporting. Agree on this, from a user perspective, installation should be more detailed and explained. 

README is updated with step by step how to setup complete service, including from build and from compiled binary.
