### ISSUE TITLE
Profile saving / setting seems broken

### ISSUE THREAD

**Issue by kondas** [jurkovic-nikola/OpenLinkHub#12]
I'm trying to create some profiles, but it seems no matter which is chosen on the GUI, the setting are applied to other profiles.

Steps to reproduce:
Fresh start of application with default configuration
Create new profile (Name TEST Sensor CPU)
Select new profile
Change ID1 rule, set fan speed to 99%
Observe that built in "Normal" profile ID1 rule fan speed changed to 99% on GUI.

Steps to reproduce:
Fresh start of application with default configuration
Create new profile (Name TEST2 Sensor CPU , Static mode enabled) 
Select new profile
Change ID1 rule, set fan speed to 100%
Create new profile (Name TEST3 Sensor CPU , Static mode enabled) 
Select new profile
Change ID1 rule, set fan speed to 100%
Observe that TEST2 profile ID1 rule fan speed changed also to 100% on GUI.

**Comment by jurkovic-nikola** [comment]
Fix will be released in 0.1.7 version
