### ISSUE TITLE
After restarting the system, the program does not start

### ISSUE THREAD

**Issue by stillGP** [jurkovic-nikola/OpenLinkHub#16]
After restarting the system, OpenLinkHub does not start. 
It starts only after typing in the terminal
➜ ~ cd OpenLinkHub/
chmod +x install.sh
sudo sh install.sh
I had no problem with earlier versions, I added it to autostart and it always started.
[stdout.log](https://github.com/user-attachments/files/17005373/stdout.log)

**Comment by jurkovic-nikola** [comment]
Check output of `sudo systemctl status OpenLinkHub.service` command

**Comment by stillGP** [comment]
This is what it looks like
![2](https://github.com/user-attachments/assets/10fdea97-fe34-495f-8d0b-244056561e56)

**Comment by jurkovic-nikola** [comment]
What happens when you restart service from terminal ? Is device working okay then or ?

**Comment by stillGP** [comment]
After starting it in the console it doesn't work.
![3](https://github.com/user-attachments/assets/2edd70f3-f8c7-4d9a-8894-01a8c5f39dd0)
Can you tell me what to do?

**Comment by jurkovic-nikola** [comment]
Just run `sudo systemctl restart OpenLinkHub.service`

**Comment by stillGP** [comment]
It worked. But why do I have to restart the service after starting the system?

**Comment by jurkovic-nikola** [comment]
> It worked. But why do I have to restart the service after starting the system?

You shouldn't, since its not working as expected. Where issue appears ? When you restart PC, Sleep / Resume or when you just shutdown and turn the PC back on ?

**Comment by stillGP** [comment]
The problem always occurs after starting the computer. What to do to prevent the problem from occurring?

**Comment by jurkovic-nikola** [comment]
Replace binary with this once and shutdown / turn on PC. After that upload content of stdout.log, i have some guesses what could be, just need initial data. Don't restart, shutdown and start PC. 

[OpenLinkHub.zip](https://github.com/user-attachments/files/17005539/OpenLinkHub.zip)

**Comment by stillGP** [comment]
It's up and running.
[stdout.log](https://github.com/user-attachments/files/17005566/stdout.log)

**Comment by jurkovic-nikola** [comment]
Okay, try with this binary. Delay has been introduced before device initialization to wait for device being ready. 
[OpenLinkHub.zip](https://github.com/user-attachments/files/17005585/OpenLinkHub.zip)

**Comment by stillGP** [comment]
Unfortunately, it doesn't work.
[stdout.log](https://github.com/user-attachments/files/17005595/stdout.log)

**Comment by jurkovic-nikola** [comment]
System lost permission towards the device
`sudo rm -rf /etc/udev/rules.d/99-corsair*`

Then:
`echo "KERNEL==\"hidraw*\", SUBSYSTEMS==\"usb\", ATTRS{idVendor}==\"1b1c\", ATTRS{idProduct}==\"0c32\", MODE=\"0666\"" | sudo tee /etc/udev/rules.d/99-corsair-cc-64.rules`

`echo "KERNEL==\"hidraw*\", SUBSYSTEMS==\"usb\", ATTRS{idVendor}==\"1b1c\", ATTRS{idProduct}==\"0c1c\", MODE=\"0666\"" | sudo tee /etc/udev/rules.d/99-corsair-cc-96.rules`

`echo "KERNEL==\"hidraw*\", SUBSYSTEMS==\"usb\", ATTRS{idVendor}==\"1b1c\", ATTRS{idProduct}==\"0c39\", MODE=\"0666\"" | sudo tee /etc/udev/rules.d/99-corsair-elite-lcd.rules`

`sudo udevadm control --reload-rules
sudo udevadm trigger`

After that try to shutdown / turn on.

**Comment by stillGP** [comment]
Unfortunately, it doesn't work.
![4](https://github.com/user-attachments/assets/30dbbdc0-572e-41d1-8611-98221c7317d3)

**Comment by jurkovic-nikola** [comment]
Whats the output of stdout now ? Last log had permission denied towards the device.

**Comment by stillGP** [comment]
Sorry for the delay, I had to go out and couldn't reply. I'm sending the file.
[stdout.log](https://github.com/user-attachments/files/17006143/stdout.log)

**Comment by jurkovic-nikola** [comment]
`sudo getfacl /dev/hidraw2` Run this command to see device permissions.

**Comment by stillGP** [comment]
➜  ~ sudo getfacl /dev/hidraw2
[sudo] hasło użytkownika gp: 
getfacl: Usunięcie wiodącego '/' ze ścieżek bezwzględnych
# file: dev/hidraw2
# owner: root
# group: root
user::rw-
user:gp:rw-
group::rw-
mask::rw-
other::rw-

**Comment by jurkovic-nikola** [comment]
Okay, permissions are fine now since device started. Shutdown and turn on PC back again, but do not run and install scripts, those script will replace binary with old one.

**Comment by stillGP** [comment]
After restarting the computer it still won't start. I guess the only option left is to restart from the terminal.;(
sudo systemctl restart OpenLinkHub.service
[stdout.log](https://github.com/user-attachments/files/17006517/stdout.log)

**Comment by jurkovic-nikola** [comment]
Can you send me stdout without manually starting it ? Log contains error even for http server binding, like there is double process running

**Comment by stillGP** [comment]
I send after restarting the computer without manual start
[stdout.log](https://github.com/user-attachments/files/17006551/stdout.log)

**Comment by jurkovic-nikola** [comment]
`sudo rm /etc/systemd/system/OpenLinkHub.service`

Run this and reboot.

**Comment by stillGP** [comment]
After entering the above command and restarting the computer, the program started. I also joined discord.
[stdout.log](https://github.com/user-attachments/files/17006604/stdout.log)

**Comment by jurkovic-nikola** [comment]
Issue is solved over Discord.
