### ISSUE TITLE
Move stuff dashboard, ASUS motherboard LEDs + Phanteks NV5 case LEDs support

### ISSUE THREAD

**Issue by iocc-git** [jurkovic-nikola/OpenLinkHub#18]
First I have to say that there is great improvements lately 😊 

**Is your feature request related to a problem? Please describe.**

1.
Because my fans isnt in the right order I wish that I could move them on the dashboard.
FAN 1, FAN 3, FAN 2 is confusing.

2.
There is two different LEDs that I cant reach with OpenLinkHub but can with
OpenRGB. Is it possible to include that functionally in OpenLinkHub?
It would be great to have everything related in one place 🙂

I got ASUS TUF GAMING B760-PLUS WIFI motherboard that got 3 LEDs and
Phanteks NV5 case with 16 LEDs.

**Describe the solution you'd like**

To be able to control the ASUS and Phanteks LEDs aswell.

**Describe alternatives you've considered**

OpenRGB is working. Kinda. Some things works and some doesnt.
Doesnt autodetect how many LEDs you got so you have to guess.

Have also tried ckb-next but it doesnt work.

**Additional context**

OpenRGB have some "colorideas" (is this even a word?) that looks interesting if they had worked.
Maybe you can be colorinspired 😁

**Comment by jurkovic-nikola** [comment]
1. Yes, will be implemented in 0.2.2 version. 
2. No. This will result in endless issues due to amount of motherboard versions in the market and amount of different RGB controllers they are using. Motherboard RGB or any motherboard RGB related stuff should not be controlled by this product.
