### ISSUE TITLE
Default configuration does not allow service to start

### ISSUE THREAD

**Issue by RobotRoss** [jurkovic-nikola/OpenLinkHub#2]
**Describe the bug**
Under the default installation process, the service is unable to launch as the configuration file is empty.

**To Reproduce**
1. Install with defaults from git.
2. Attempt to start service
3. Read service status. Observe a line similar to below:
```
Jul 09 15:46:18 hortonator OpenLinkHub[30304]: [Temperatures] Loading profile: /usr/bin/OpenLinkHub/database/temperatures/empty
Jul 09 15:46:18 hortonator OpenLinkHub[30304]: {"error":"EOF","level":"fatal","location":"/usr/bin/OpenLinkHub/database/temperatures/empty","msg":"Unable to read temperature profile","time":"2024-07-09T15:46:18+01:00"}
```

**Expected behavior**
The service should start without a configuration, or the default configuration should be changed to allow the service to start.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Fedora 40
 - Browser Firefox
 - Version 127

**Comment by jurkovic-nikola** [comment]
This is resolved in latest commit and build.
