### ISSUE TITLE
Easy way to turn on/off all light

### ISSUE THREAD

**Issue by iocc-git** [jurkovic-nikola/OpenLinkHub#22]
**Is your feature request related to a problem? Please describe.**

Easy way to turn on/off all light. Possible time scheduled aswell.

**Describe the solution you'd like**

I cant sleep with the lights on.

My "iCUE LINK System Hub" miss a 0% for "power" turned off.
My CPU and FANs got "off" mode.

However its will take alot of time to that every night, its
faster to just put a hoodie over it, not entirely but enough.

When I think about it I want a on/off switch but also scheduled
lights off and on. A button for on/off on the dashboard and
one for scheduled?

So 22:30 it switches off the lights and turn them on 07:30
every day. Maybe you want to be able to set diffrent times
on all seven days.

**Describe alternatives you've considered**

...

**Additional context**

🙂

**Comment by jurkovic-nikola** [comment]
You already have off RGB mode per device. 

![Screenshot from 2024-11-03 20-40-57](https://github.com/user-attachments/assets/607ea03a-69a9-4245-8f18-a7197dd3a5bd)

I'm having hard time understanding "off" mode. Once you turn off PC, Link System Hub is off without any power and there is no way fans are lighting up while PCIE power is off, since PCIE power is powering the lights.

**Comment by iocc-git** [comment]
Right, now I noticed off there.
It works but never updates the latest choice. It always says circle.

I never turn off my PC - its also router and server.

**Comment by jurkovic-nikola** [comment]
Well, guess scheduler can be implemented. I'll see for 0.3.1 or 0.3.2 version.

**Comment by iocc-git** [comment]
Great 😊

**Comment by jurkovic-nikola** [comment]
Scheduler implemented in 0.3.1

**Comment by iocc-git** [comment]
Thanks, works just fine 🙂

**Comment by iocc-git** [comment]
After a while I realized that it has a bug.
It will only turn off if the off time and the on time is on the same "day".
So off 22:35 and on (the next day) 07:00 will not work.

No errors and its correct in scheduler.json.
The logfile doesnt say anything about it what I can see.
Off just doesnt happend.

Here is the logfile and scheduler.json.
No off for 2024-11-19 22:35 and the lights is still on.
[scheduler.json](https://github.com/user-attachments/files/17821968/scheduler.json)
[stdout.log](https://github.com/user-attachments/files/17821971/stdout.log)

**Comment by jurkovic-nikola** [comment]
There wont be any logs. I'll fix it today with different schedule code.

**Comment by iocc-git** [comment]
It works now but with a twist. It turns off the leds 19:55 and starts them again 19:59 🤔
I have
     "rgbOff": "23:45",
    "rgbOn": "08:30"      ...and are running OpenLinkHub-0.3.6-1.x86_64.

I think it got sad when I deleted all profiles except the one that Im
using. But sometimes it seems to be looking for it without my "added" name.

Whats the right way to do?
[stdout.log](https://github.com/user-attachments/files/17999043/stdout.log)

**Comment by jurkovic-nikola** [comment]
Hey, I've put same values as yours, lets see what will happen.

**Comment by iocc-git** [comment]
Did you notice anything similar to me?

Now Im running OpenLinkHub-0.4.0.
I have also noticed if I press save it will only say  RGB.... successfully updated if its enabled.
But if the enable isnt checked it will not say anything when I press save.

**Comment by jurkovic-nikola** [comment]
Couple of things changed, left it on test machine for 2 days. So far so good, no issues for now. Gonna leave it for couple of days more.
