### ISSUE TITLE
New user, couple of questions

### ISSUE THREAD

**Issue by oparada1988** [jurkovic-nikola/OpenLinkHub#29]
1 Where is "database/rgb.json" located? Installed the .deb file on ubuntu 24.04

2. How can I get the color profile the "iCUE Link Titan 240 RX" comes out of the box? [This one](https://www.amazon.com/dp/B0D6BF3RXL?ref=ppx_yo2ov_dt_b_fed_asin_title)

Thanks in advance

**Comment by jurkovic-nikola** [comment]
1. rgb.json is located in /opt/OpenLinkHub/database/ folder.

2. This is default hardware color of the device. Something close to this would be watercolor effect. This software does not copy any RGB mode that you can find in iCUE.

**Comment by oparada1988** [comment]
Wow, thank you for your promp response, I will continue to mess with it. Really like it so far :-)
