### ISSUE TITLE
Commander pro Temperature Sensor

### ISSUE THREAD

**Issue by cnschu** [jurkovic-nikola/OpenLinkHub#30]
**Describe the bug**
Temperature sensor reads far too low Temperature.

**To Reproduce**
1. installed a temperature sensor in my custom water loop
2. connected the sensor to the commander PRO
3. water temperature in windows icue shows around 28 Celsius
4. water temperature in OpenLinkHub shows around 3-5 Celsius

**Expected behavior**
Water temperature in OpenLinkHub is equal to the Temperature shown in iCue.

**Screenshots**
![image](https://github.com/user-attachments/assets/633f1905-8bb2-4b7c-bbac-b0e277d97fa2)
![grafik](https://github.com/user-attachments/assets/86452a53-32a0-47ea-9ba1-59df1b3b1eec)

**Desktop (please complete the following information):**
- OS: Linux Mint 22 Cinnamon
-  Device Firmware: 0.9.212
- Browser: Firefox
- Version: 0.3.3_amd64

**not BUG related**
Love your work, it's a great tool

**Comment by jurkovic-nikola** [comment]
Hello,

This is caused by using lm-sensors or any other package that can interact with this device since its supported in the kernel. It also messes up fan speeds.

**Comment by cnschu** [comment]
thanks.
its resolved.
