### ISSUE TITLE
triple 6 perms on hidraw device

### ISSUE THREAD

**Issue by jamcinnes2** [jurkovic-nikola/OpenLinkHub#41]
**Is your feature request related to a problem? Please describe.**
Is it necessary to give rw (666) permissions to the hidraw keyboard device? There are udev rules specifying mode 0666 for my keyboard. I'm ignorant maybe this is just fine... ?

**Describe the solution you'd like**
Concerned about giving rw to everyone.

**Describe alternatives you've considered**
Restrict mode on hidraw device.

**Additional context**

**Comment by jamcinnes2** [comment]
p.s. this is awesome, my LEDs work great

**Comment by jurkovic-nikola** [comment]
Hello,

Thank you for reporting. Permissions are changed to 600 and locked to `openlinkhub` username.
