### ISSUE TITLE
is ICUE profile importing planned?

### ISSUE THREAD

**Issue by Melk047** [jurkovic-nikola/OpenLinkHub#46]
like the title says, or even animated custom profiles? (for keyboards) sorry if this has been asked for before, i didnt see it in issues though.

**Comment by jurkovic-nikola** [comment]
Hello,

It's not planned at all. Current plan is basic device implementation, after that key-rebinds and macros for keyboard and mouse.

**Comment by Melk047** [comment]
darn okay
