### ISSUE TITLE
(RGB/Lighting) AF/AR Series fan support?

### ISSUE THREAD

**Issue by JustaFloatingEyeYT** [jurkovic-nikola/OpenLinkHub#47]
**Describe the solution you'd like**
So I noticed there's an option for lighting in the app. Great! I can finally use my fan lights (they were white by default and when I installed the app they turned off) as well as change the fan speeds of course. But I notice that none of the fan options work as my fans are an AF/AR series and that is not one of the options. 

So will there be support for these fans or am I doing something wrong?

**Comment by jurkovic-nikola** [comment]
What controller do you have to control them ? Send me lsusb output

**Comment by JustaFloatingEyeYT** [comment]
![image](https://github.com/user-attachments/assets/954c5249-fc9a-438d-9825-14d81e7b4bdb)
I'm not sure if this is what you mean by controller but its this fanhub here.

And I am not sure where I find the lsusb output?

**Comment by jurkovic-nikola** [comment]
Is your fan rgb cable 3 pin or 4 pin ?

**Comment by JustaFloatingEyeYT** [comment]
4 pin

**Comment by jurkovic-nikola** [comment]
Are they directly connected to Commander Core XT RGB PPRTA or you're using Lighting Node connected to XT ?

**Comment by JustaFloatingEyeYT** [comment]
i think im using the built in rgb hub with the 5000d (case im using)

**Comment by jurkovic-nikola** [comment]
Send me image of how it's connected in the case. 4pin rgb fans are automatically detected if connected directly to Commander Core XT

**Comment by JustaFloatingEyeYT** [comment]
![20241230_223633](https://github.com/user-attachments/assets/42e2f442-1611-4746-a23d-436a7f975b5e)

**Comment by JustaFloatingEyeYT** [comment]
The 3 fans at the top do connect to the fan hub too I am certain. as the app detects 4 fans.

**Comment by jurkovic-nikola** [comment]
Yeah, thats Corsair RGB Hub. Set on Commander Core XT page 3 pin Corsair hub fans to 8 led fan and set amount. This should activate the rgb on fans to default blue color.

**Comment by JustaFloatingEyeYT** [comment]
I am not sure if the cables could reach but ill try that

**Comment by JustaFloatingEyeYT** [comment]
![image](https://github.com/user-attachments/assets/ab9dc22c-d9fc-4950-89d0-323ee84add4f)
They are working and light up!

How do I change the colour though?

**Comment by jurkovic-nikola** [comment]
There is file for each device in dstabase/rgb folder jn /opt/OpenLinkHub. Colors are changed there until RGB editor is implemented.

**Comment by JustaFloatingEyeYT** [comment]
Alright, thanks!
