### ISSUE TITLE
Temperature profile controlled by AiO Sensor (fluid temperature)

### ISSUE THREAD

**Issue by stillGP** [jurkovic-nikola/OpenLinkHub#5]
Is it possible to set a temperature profile that would be controlled by the AiO temperature sensor? The scale is from 34 to 50 every 2 degrees, respectively 32,34,36,38,40,42,44,46,48,50. This is a more stable reading and the fans do not go crazy. By the way, I would like to thank you for the work you put in, I can finally control the fan speeds.

**Comment by jurkovic-nikola** [comment]
Hello,

I'll look into it. Considering we already have all the data, this is just a switch what temperature to use with what profile.

**Comment by jurkovic-nikola** [comment]
This is implemented in 0.1.1 release. Profile will create default values, but you can change them to fit your needs.

**Comment by stillGP** [comment]
Thank you very much, works great. There was one small cosmetic error.
![Liquid](https://github.com/user-attachments/assets/d2bda35d-7882-4667-9a90-5d5d6fdb1694)

**Comment by jurkovic-nikola** [comment]
Package re-uploaded. Should be OK now.

**Comment by stillGP** [comment]
Thank you very much. You are a champion.
