### ISSUE TITLE
RGB - does not change the fan backlight

### ISSUE THREAD

**Issue by stillGP** [jurkovic-nikola/OpenLinkHub#6]
The RGB profile changes the backlight only in the pump and there is no backlight in the fans.
My AiO is LCD iCUE H170i ELITE which is detected like this:
Bus 001 Device 005: ID 1b1c:0c1c Corsair CORSAIR iCUE Commander CORE
Bus 001 Device 009: ID 1b1c:0c39 Corsair LCD Cap for Elite Capellix coolers
![1](https://github.com/user-attachments/assets/b62a8040-050b-4290-8bb0-f0128f7b0a66)
![2](https://github.com/user-attachments/assets/452e49d2-7ca9-4397-84e6-71f8fc578500)
![3](https://github.com/user-attachments/assets/8508aa2c-b161-444f-8512-365a18e14443)

**Comment by jurkovic-nikola** [comment]
Is your fan RGB port wired in same port number as PWM wire ? Like Fan 1 PWM goes to hub PWD port 1 and RGB likewise.

**Comment by stillGP** [comment]
The fans and pump are connected to COMMANDER CORE as shown in the photo. One wire goes from the pump to the CPU fan on the motherboard (pump speed).
![1](https://github.com/user-attachments/assets/d465a1e1-2a09-4a18-82b3-e9f8b3ee8fa8)

**Comment by jurkovic-nikola** [comment]
Okay, thats good. Can you replace the OpenLinkHub binary with debug one and send me stdout.log after program is started. Debug version attached. 
[debug.zip](https://github.com/user-attachments/files/16573455/debug.zip)

**Comment by stillGP** [comment]
Of course. I'm sending the file.
[stdout.log](https://github.com/user-attachments/files/16573471/stdout.log)

**Comment by jurkovic-nikola** [comment]
Okay, LED data looks okay by values. Lets run another debug with new file to see why AIO is not detected. Same process as before, replace binary and upload stdout
[debug.zip](https://github.com/user-attachments/files/16573493/debug.zip)

**Comment by stillGP** [comment]
[stdout.log](https://github.com/user-attachments/files/16573507/stdout.log)

**Comment by jurkovic-nikola** [comment]
Lets see if this is detect AIO and LED channels on the pump. 
[test.zip](https://github.com/user-attachments/files/16573542/test.zip)

**Comment by stillGP** [comment]
It detected the name ;)

[stdout.log](https://github.com/user-attachments/files/16573556/stdout.log)
![2024-08-11_13-53](https://github.com/user-attachments/assets/edb039dd-26c7-46d7-a03d-66a554366576)

**Comment by jurkovic-nikola** [comment]
Good, packet for pumo / radiator was missing second one. Lets see led data now per channel. 
[debug.zip](https://github.com/user-attachments/files/16573568/debug.zip)

**Comment by stillGP** [comment]
Unfortunately, RGB only works on the pump.
[stdout.log](https://github.com/user-attachments/files/16573641/stdout.log)

**Comment by jurkovic-nikola** [comment]
Nah, pump LEDs are not detected. You just have a combination of 3 detected fans with 8 LEDs and your pump has 24 LEDs, whats why 'pump' works, when in reality those 24 LEDS that are working are actually fan LEDs combined. Lets try with this version. 
[debug.zip](https://github.com/user-attachments/files/16573700/debug.zip)

**Comment by stillGP** [comment]
[stdout.log](https://github.com/user-attachments/files/16573741/stdout.log)

**Comment by jurkovic-nikola** [comment]
You're welcome. Thank you too for testing those multiple versions. 

`{"LED Channel":0,"connected":true,"level":"info","msg":"LED debug","numLEDs":24,"time":"2024-08-11T14:53:16+02:00"}
{"LED Channel":1,"connected":true,"level":"info","msg":"LED debug","numLEDs":8,"time":"2024-08-11T14:53:16+02:00"}
{"LED Channel":2,"connected":true,"level":"info","msg":"LED debug","numLEDs":8,"time":"2024-08-11T14:53:16+02:00"}
{"LED Channel":3,"connected":true,"level":"info","msg":"LED debug","numLEDs":8,"time":"2024-08-11T14:53:16+02:00"}`

This is how it should look like, Channel 0 is always pump, rest are Commander Core physical LED ports. I'm gonna release new version without all those debug info inside.
