### ISSUE TITLE
0.1.4-beta doesn't work

### ISSUE THREAD

**Issue by stillGP** [jurkovic-nikola/OpenLinkHub#7]
It starts, the fans start working faster and after a while it turns off. I can't connect to the settings http://127.0.0.1:27003/

➜  ~ lsusb -d 1b1c:
Bus 001 Device 004: ID 1b1c:0c1c Corsair CORSAIR iCUE Commander CORE
Bus 001 Device 008: ID 1b1c:0c39 Corsair LCD Cap for Elite Capellix coolers

[stdout.log](https://github.com/user-attachments/files/16627403/stdout.log)

**Comment by jurkovic-nikola** [comment]
Resolved and package re-published. I've never tested on empty profile.

**Comment by stillGP** [comment]
It works now. This new LCD option changes the font of the fluid temperature but does not want to change to others, e.g. CPU, GPU or combined.
![1](https://github.com/user-attachments/assets/c86b57c7-8098-4e33-ae22-dde7670c25b2)

**Comment by jurkovic-nikola** [comment]
Did you replace both web/ and static/ folders ? There is JS change

**Comment by stillGP** [comment]
Yes, first I deleted everything and reinstalled it.

**Comment by jurkovic-nikola** [comment]
Can you view page source on device and click on the bottom of page on overview.js file and refresh it. 
![Screenshot from 2024-08-15 19-08-33](https://github.com/user-attachments/assets/d88bb2ba-f355-4bae-8def-066ec12fc121)

Maybe its cache related.

**Comment by stillGP** [comment]
It works. You are a master. Thank you.
![2](https://github.com/user-attachments/assets/d122a39c-a10c-4213-8fe4-c0e094bc302a)

**Comment by jurkovic-nikola** [comment]
Awesome. I'll implement no-cache in http code so this does not happen.
